### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by dukex** [uhuraapp/uhura-frontend#106]
As I am a unauthenticated user
To see my subscriptions list
I want to login 

- [x] Scenario 1: Password is required

Given I'm on login page
When I fill the email field with 'x@com'
And click on 'Login' button
Then I need see a message about password is required 

- [x] Scenario 2: Email and password should be match 

Given I'm on login page
When I fill the email field with 'x@com'
And I fill the password field with 'x'
And click on 'Login' button
Then I need see a message about email or password don't match 
- [ ] ~~Scenario 3: Should send user to subscriptions list~~

~~Given I'm on login page~~
~~And my email ' x@com' exists~~
~~And my password is ' x'~~
~~When I fill the email field with ' x@com'~~
~~And I fill the password field with 'x'~~
~~And I click on 'Login'~~
~~Then I need see my subscriptions list~~ 
Moved to https://github.com/uhuraapp/uhura-frontend/issues/123

- [x] Scenario 4: Enter in oauth flow

Given I'm on login page
When I click on 'Sign in Facebook'
Then I need enter into oauth flow 

- [x] Scenario 5: Accept oauth 

Given I'm into oauth flow
When I accept login 
Then I need see my subscriptions list

- [x] Scenario 6: Denied oauth 

Given I'm into oauth flow
When I denied login
Then I need see a message about login denied

**Comment by fonzi** [comment]
Will .com be a required email extension, or is it just for scenario purposes?

**Comment by dukex** [comment]
It's just for scenario purpose. Today don't have any kind of input validation in frontend.

**Comment by dukex** [comment]
Moved login via email/password to https://github.com/uhuraapp/uhura-frontend/issues/123
