### ISSUE TITLE
Share Modal "Close" button does not respond

### ISSUE THREAD

**Issue by fonzi** [uhuraapp/uhura-frontend#119]
At the moment both in firefox and chrome, the close button from the share modal does not respond.
Only way to get out is to click outside of the modal. 

I am not getting any logs, in the web console at the moment. 

Except for : which does not matter most likely. 
```
Application Cache Error event: Manifest fetch failed (404) http://localhost:4200/manifest.appcache
Unrecognized Content-Security-Policy directive 'content-src'.
exports.init @ content.js:68init @ content.js:357(anonymous function) @ content.js:382(anonymous function) @ content.js:383
```

![1](https://cloud.githubusercontent.com/assets/626330/9569890/87f68826-4f2e-11e5-8e73-77e9ecf23ffd.png)

**Comment by dukex** [comment]
@fonzi fixed!

**Comment by fonzi** [comment]
@dukex +1 this really makes a difference, the app starts to feel complete.
