### ISSUE TITLE
Login page, one field is in English other in Portuguese 

### ISSUE THREAD

**Issue by fonzi** [uhuraapp/uhura-frontend#122]
Under the login page, one field is in English (Email) other field is in Portuguese (password)
Seems that the login page is mostly in English. 

![1](https://cloud.githubusercontent.com/assets/626330/9570713/c3819350-4f46-11e5-9819-414fcd40c6b0.png)

**Comment by dukex** [comment]
Closed via commit, but do you test and reopen if necessary.

**Comment by dukex** [comment]
@fonzi I reopen here

**Comment by fonzi** [comment]
The string is now in English.
