### ISSUE TITLE
Terms of Use

### ISSUE THREAD

**Issue by dukex** [uhuraapp/uhura-frontend#124]
- [x] Write
- [x] Review
- [ ] Publish

**Comment by dukex** [comment]
Hi @fonzi do you can help with the review? I need make a double check but a review by you will be awesome.

ps: I share with you the file

**Comment by dukex** [comment]
@fonzi closed here but you can it soon in uhura.io or at https://github.com/uhuraapp/uhura-frontend/commit/f9ab67318e1b2b7fec513990b2dded7b9d9b1c74 and submit a pull request

**Comment by fonzi** [comment]
Okay. I'll take a look. Apologize for the delay. I'll have some time this
weekend to verify it.

**Comment by dukex** [comment]
Thank you @fonzi, don't worry about it. I'm doing the things in the best way, when you have time you can review and we can discuss about.
