### ISSUE TITLE
We allow non emails to sign up

### ISSUE THREAD

**Issue by fonzi** [uhuraapp/uhura-frontend#136]
In the register branch we allow users to signup without a proper email. We should only allow emails to be entered in the email field or specify that you do not need an email. 

Go to /register
Enter test information name
Enter a email like test.fonzi.tk (This is not a valid email, we should have a regex like (http://ex-parrot.com/~pdw/Mail-RFC822-Address.html) Or we can whip something up

@dukex Let me know if you want me to whip up a simpler regex (it may not be a fool proof regex but should only allow emails.

**Comment by fonzi** [comment]
Here is a simpler version of js. Per w3 : http://www.w3.org/TR/html5/forms.html#valid-e-mail-address

**Comment by dukex** [comment]
Thank you @fonzi I'll to use the w3 version
