### ISSUE TITLE
Subscription not visuable

### ISSUE THREAD

**Issue by broerse** [uhuraapp/uhura-frontend#164]
On https://uhura.io/profiles/157 my Subscriptions don't show. To try to fix this I deleted my account. It seems deleting it will not remove it because now I can't create an account on the same gmail login. I get "Error: Could not authenticate using external service". Maybe this is not one issue.

**Comment by dukex** [comment]
Hi @broerse, I restore your account now you can login again.

The https://uhura.io/profiles/157 is showing the 'Ember Weekend' podcast, this is correct?

**Comment by broerse** [comment]
Yes that is correct. Login works! Thanks. There is still no way to find new podcasts in my account. Manually going to https://uhura.io/channels/ gives me nothing. It still feels like my account is broken.

**Comment by dukex** [comment]
@broerse I'm working to add a way to find channel on the version running in http://uhura.io, this is my focus now but today only the version running in http://uhuraapp.com has a channel finder

**Comment by broerse** [comment]
Clear! Hope you can add that soon.
