### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'blanket.options('cliOptions').autostart')

### ISSUE THREAD

**Issue by dukex** [uhuraapp/uhura-frontend#92]
View details in Rollbar: [https://rollbar.com/uhura-dashboard/uhura-frontend/items/67/](https://rollbar.com/uhura-dashboard/uhura-frontend/items/67/)

```

TypeError: undefined is not an object (evaluating 'blanket.options('cliOptions').autostart')
  File "http://localhost:7357/assets/test-loader.js", line 74, in [anonymous]
```

**Comment by Suven** [comment]
Hey!

I ran into the same issue. Do you remember how you solved that?

**Comment by dukex** [comment]
Hi @Suven 

I don't remember exactly but I need to change a lot the configuration file: [blanket-coptions](https://github.com/uhuraapp/uhura-frontend/blob/211c678622d3ec97fcb56fb09b2211e345cc23f0/tests/blanket-options.js)
